"""empty message

Revision ID: 02e94f620ab3
Revises: da382cfad87b
Create Date: 2024-09-25 10:49:36.382494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e94f620ab3'
down_revision: Union[str, None] = 'da382cfad87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_items', sa.Column('discount_count', sa.Integer(), nullable=True))
    op.add_column('miner_items', sa.Column('discount_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_items', 'discount_value')
    op.drop_column('miner_items', 'discount_count')
    # ### end Alembic commands ###
