"""empty message

Revision ID: 15ef4b06d8fe
Revises: 2893c4f244ba
Create Date: 2024-08-26 19:19:55.260017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ef4b06d8fe'
down_revision: Union[str, None] = '2893c4f244ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_items_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('miner_items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'miner_items', 'miner_items_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'miner_items', type_='foreignkey')
    op.drop_column('miner_items', 'category_id')
    op.drop_table('miner_items_categories')
    # ### end Alembic commands ###
