"""empty message

Revision ID: 2893c4f244ba
Revises: 3e77eae3dd13
Create Date: 2024-08-26 14:19:14.796053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2893c4f244ba'
down_revision: Union[str, None] = '3e77eae3dd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.String(length=32), nullable=True))
    op.drop_column('messages', 'sender_name')
    op.drop_column('messages', 'isCustomerMessage')
    op.add_column('tickets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tickets', 'customer_id')
    op.drop_column('tickets', 'opened')
    op.drop_column('tickets', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('opened', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'is_open')
    op.drop_column('tickets', 'user_id')
    op.add_column('messages', sa.Column('isCustomerMessage', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###
