"""empty message

Revision ID: 2e6896770338
Revises: 8a8f52ea6977
Create Date: 2024-08-13 12:03:40.096041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e6896770338'
down_revision: Union[str, None] = '8a8f52ea6977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payments_sites')
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('current_balance', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments_sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='payments_sites_payment_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payments_sites_pkey')
    )
    op.drop_table('hostings')
    # ### end Alembic commands ###
