"""empty message

Revision ID: 3e77eae3dd13
Revises: 7fc0dfae9d8a
Create Date: 2024-08-22 19:30:22.860463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e77eae3dd13'
down_revision: Union[str, None] = '7fc0dfae9d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_items', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_items', 'priority')
    # ### end Alembic commands ###
