"""empty message

Revision ID: 41255ede5ec7
Revises: 9a3330b668d7
Create Date: 2024-08-17 10:45:37.714973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41255ede5ec7'
down_revision: Union[str, None] = '9a3330b668d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('payment_data', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'payment_data')
    # ### end Alembic commands ###
