"""empty message

Revision ID: 447b0517aaa1
Revises: da335d4b6181
Create Date: 2024-09-06 08:39:59.010350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447b0517aaa1'
down_revision: Union[str, None] = 'da335d4b6181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billings', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_column('billings', 'image_id')
    # ### end Alembic commands ###
