"""empty message

Revision ID: 5fa38ee4ac90
Revises: b4bad818c048
Create Date: 2024-08-10 12:21:26.756364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa38ee4ac90'
down_revision: Union[str, None] = 'b4bad818c048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_items', 'consumption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_items', sa.Column('consumption', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
