"""empty message

Revision ID: 75f3a8e0b23d
Revises: 4fe74c122160
Create Date: 2024-08-16 13:05:30.696107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f3a8e0b23d'
down_revision: Union[str, None] = '4fe74c122160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings_buy_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('buy_request_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buy_request_id'], ['buy_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_id')
    )
    op.add_column('buy_requests', sa.Column('state', sa.String(length=32), nullable=True))
    op.drop_column('buy_requests', 'status')
    op.add_column('markets_carts', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets_carts', 'count')
    op.add_column('buy_requests', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('buy_requests', 'state')
    op.drop_table('billings_buy_requests')
    # ### end Alembic commands ###
