"""empty message

Revision ID: 886413e586fc
Revises: e789982def76
Create Date: 2024-08-14 09:58:53.183965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '886413e586fc'
down_revision: Union[str, None] = 'e789982def76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('payments_hostings')
    op.drop_table('hostings')
    op.add_column('employees', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'created')
    op.create_table('hostings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hostings_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='hostings_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='hostings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments_hostings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hosting_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hosting_id'], ['hostings.id'], name='payments_hostings_hosting_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='payments_hostings_payment_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payments_hostings_pkey'),
    sa.UniqueConstraint('hosting_id', name='payments_hostings_hosting_id_key')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('value', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    # ### end Alembic commands ###
