"""empty message

Revision ID: 9a3330b668d7
Revises: c9bf8c1b19cd
Create Date: 2024-08-17 00:01:02.808512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3330b668d7'
down_revision: Union[str, None] = 'c9bf8c1b19cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_items', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'miner_items', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('miner_items', 'image')
    op.add_column('users', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'image_id')
    op.add_column('miner_items', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'miner_items', type_='foreignkey')
    op.drop_column('miner_items', 'image_id')
    # ### end Alembic commands ###
