"""empty message

Revision ID: 9e8e571931f0
Revises: 02e94f620ab3
Create Date: 2024-10-10 10:12:47.350417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8e571931f0'
down_revision: Union[str, None] = '02e94f620ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('id_str', sa.String(length=64), nullable=True))
    op.add_column('workers', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('workers', sa.Column('behavior', sa.String(length=32), nullable=True))
    op.add_column('workers', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('workers', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_constraint('workers_worker_id_key', 'workers', type_='unique')
    op.drop_constraint('workers_worker_name_key', 'workers', type_='unique')
    op.drop_column('workers', 'worker_name')
    op.drop_column('workers', 'hashrate')
    op.drop_column('workers', 'worker_id')
    op.drop_column('workers', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('worker_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('hashrate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('worker_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('workers_worker_name_key', 'workers', ['worker_name'])
    op.create_unique_constraint('workers_worker_id_key', 'workers', ['worker_id'])
    op.drop_column('workers', 'created')
    op.drop_column('workers', 'hidden')
    op.drop_column('workers', 'behavior')
    op.drop_column('workers', 'name')
    op.drop_column('workers', 'id_str')
    # ### end Alembic commands ###
