"""empty message

Revision ID: c9bf8c1b19cd
Revises: dbfa00c2c1eb
Create Date: 2024-08-16 19:17:47.102457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bf8c1b19cd'
down_revision: Union[str, None] = 'dbfa00c2c1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=8), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
