"""empty message

Revision ID: da335d4b6181
Revises: 6db8d9ed11de
Create Date: 2024-08-31 07:48:27.487172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da335d4b6181'
down_revision: Union[str, None] = '6db8d9ed11de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('currency', sa.String(length=32), nullable=True))
    op.add_column('billings', sa.Column('value_usd', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'value_usd')
    op.drop_column('billings', 'currency')
    # ### end Alembic commands ###
