"""empty message

Revision ID: f27c7c39aef8
Revises: 312bb00c859f
Create Date: 2024-08-09 14:54:11.255235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27c7c39aef8'
down_revision: Union[str, None] = '312bb00c859f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_items', sa.Column('description', sa.String(), nullable=True))
    op.add_column('miner_items', sa.Column('hash_rate', sa.BigInteger(), nullable=True))
    op.add_column('miner_items', sa.Column('energy_consumption', sa.Integer(), nullable=True))
    op.add_column('miner_items', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('miner_items', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.drop_column('miner_items', 'hidden')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_items', sa.Column('hidden', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('miner_items', 'is_hidden')
    op.drop_column('miner_items', 'price')
    op.drop_column('miner_items', 'energy_consumption')
    op.drop_column('miner_items', 'hash_rate')
    op.drop_column('miner_items', 'description')
    # ### end Alembic commands ###
